### ISSUE TITLE
Status of this module

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/datatable#1]
Hi @AlexHoebart-ICPDR. Thanks for porting this! I noticed that there is no release. Does this module work?

**Comment by AlexHoebart-ICPDR** [comment]
Yes, it should, but I haven't had time to test it thoroughly - for me it's part of a bigger migration project. 
I would appreciate any testing. It can be easily used as a Views Display.

**Comment by argiepiano** [comment]
Thanks, Alex. I am looking to use the API with a `tableselect` element, but currently the module's theming function `theme_datatable` wraps only the `table` element. I may attempt to do a PR to offer a second theming option to wrap around `tableselect`.

I did test the API and it seems to work fine. There are some errors in the documentation of `theme_datatable` that took a while to figure out. I'll do a PR for that here.

**Comment by argiepiano** [comment]
@AlexHoebart-ICPDR I've submitted a PR that improves the documentation of the theming function to make it clearer how to use it. The current documentation of how to pass parameters to `DataTable` is very confusing - I had to analyze the function itself to understand how to do it. I added a simple example about this.

**Comment by AlexHoebart-ICPDR** [comment]
Thank you very much @argiepiano. Sorry, I did not touch the theme function yet, this was still from D7. I have never used tableselect so far. I will have a look at your PR asap.
