### ISSUE TITLE
JS errors when passing an empty array for 'rows'

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/datatable#6]
When use the theming call for `datatables`, if you pass an empty array for 'rows' (a common occurrence that is handled fine by the regular table theming), Datatables generates Javascript errors:

<img width="443" alt="Screen Shot 2024-11-25 at 7 40 38 PM" src="https://github.com/user-attachments/assets/5caf3e1d-eeb2-4253-a446-708a421c47a7">

To reproduce, run the following in Devel's Execute PHP, or in a custom module:

`theme('datatable', array('header' => array('one', two'), 'rows' => array()));`

The issue is that the theming function checks $rows with `isset()` instead of `empty()`. You can see that `theme_table()` actually [uses](https://github.com/backdrop/backdrop/blob/b909b8c6d2bb2a7c98e41ff850f0d44c6a62440d/core/includes/theme.inc#L2205) `empty()` to check the rows.  

I think the solution is to change isset for empty.

**Comment by AlexHoebart-ICPDR** [comment]
Thanks very much for reporting this. I corrected it as you suggested. Made an alpha release!
